#!/bin/sh
# udhcpc default script

RESOLV_CONF="/etc/resolv.conf"

case "$1" in
    deconfig)
        ifconfig $interface 0.0.0.0
        ;;
    renew|bound)
        ifconfig $interface $ip netmask $subnet
        if [ -n "$router" ]; then
            ip route del default via 0.0.0.0 dev $interface 2>/dev/null
            ip route add default via $router dev $interface
        fi
        echo "nameserver $dns" > $RESOLV_CONF
        ;;
esac
