#!/bin/sh
echo missing dependencies:
counta=$(ls /etc/installer | grep -c "hwdata")
countb=$(ls /etc/installer | grep -c "musl")
if [ "$((counta))" -eq 0 ]; then
	echo hwdata
fi
if [ "$((countb))" -eq 0 ]; then
	echo musl
fi
