#!/bin/sh
echo uninstalling ncurses
rm /usr/share/tabset/vt300
rm /usr/share/tabset/stdcrt
rm /usr/share/tabset/vt100
rm /usr/share/tabset/std
rm /usr/bin/ncursesw6-config
rm /usr/lib/libformw.so.6
rm /usr/lib/libpanelw.so.6
rm /usr/lib/libncursesw.so
rm /usr/lib/libpanelw.so.6.4
rm /usr/lib/libformw.so
rm /usr/lib/libncursesw.so.6
rm /usr/lib/libmenuw.so.6.4
rm /usr/lib/libncursesw.so.6.4
rm /usr/lib/libmenuw.so.6
rm /usr/lib/libpanelw.so
rm /usr/lib/libmenuw.so
rm /usr/lib/libformw.so.6.4
rmdir /usr
rmdir /usr/share
rmdir /usr/share/tabset
rmdir /usr/bin
rmdir /usr/lib
