#!/bin/sh

if [ "$1" = "help" ] ; then
	echo "hardcore linux package manager (AKA flashman)"
	echo options:
	echo
	echo "install pkgdir"
	echo "installs a package from a tar archive (requires root)"
	echo
	echo "uninstall pkg"
	echo "uninstalls a package by name (requires root)"
	echo
	echo "info pkg"
	echo "shows info about a package, potentially including dependencies (might require root)"
elif [ "$1" = "install" ] ; then
	tar x -zf $2 -C /
	NAME="${2%.*}"
	sh /etc/installer/$(basename $NAME)/install
elif [ "$1" = "uninstall" ] ; then
	sh /etc/installer/$2/uninstall
	rm -r /etc/installer/$2
	echo broken packages:
	cat  /etc/installer/*/pkinfo | grep $2 | grep -Eo '^[^ ]+'
elif [ "$1" = "info" ] ; then
	NAME="${2%.*}"
	cat /etc/installer/$(basename $NAME)/pkinfo
elif [ "$1" = "list" ] ; then
	ls /etc/installer
else
	echo run flashman help
fi
