#!/bin/sh

case "$1" in
		"start")
			if [ $(grep -c "$2" /system/tmp/services) == "0" ]; then
				echo $2 >> /system/tmp/services
			fi
			;;
		"stop")
			echo "$(grep -v "$2" /system/tmp/services)" > /system/tmp/services
			kill -9 "-$(pgrep -x "$(ls /system/services | grep $2)")"
			;;
		"info")
			TMP=$(ls /system/services | grep "$2") 
			echo "info of ${TMP:6}"
			RUNNING=0
			echo "status: $(
					if [ $(grep -c "$2" /system/tmp/services) == "0" ]; then                                                                                         
                                        	echo stopped
                        		else
						echo running
						RUNNING=1
					
						echo '  PID USER  CPU_TIME CMD'
						ps -e | grep "/system/services/$(ls /system/services | grep $2)" | grep -v grep
						pstree $(pgrep -x "$(ls /system/services | grep $2)")
					fi)"
esac
